SiteHomeBundle_homepage:
    pattern:  /
    defaults: { _controller:SiteHomeBundle:Default:index }

SiteHomeBundle_contact:
    pattern: /contact 
    defaults: { _controller:SiteHomeBundle:Default:viewPageContact }
    
SiteHomeBundle_lacarte:
    pattern: /la-carte
    defaults: { _controller:SiteHomeBundle:Default:viewPageLaCarte }
    
SiteHomeBundle_labricopub:
    pattern: /la-bricopub
    defaults: { _controller:SiteHomeBundle:Default:viewPageLaBricopub }
    
